# Generated by Django 4.1.5 on 2023-03-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='name')),
                ('color', models.CharField(default='#dee2e6', max_length=7, verbose_name='color')),
                ('index', models.IntegerField(unique=True, verbose_name='index')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gitlab_label_id', models.IntegerField(db_index=True, verbose_name='gitlab label id')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', related_query_name='label', to='teams.column', verbose_name='column')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='column',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', related_query_name='column', to='teams.team', verbose_name='team'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gitlab_project_id', models.IntegerField(db_index=True, verbose_name='gitlab project id')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='project', to='teams.team', verbose_name='project')),
            ],
            options={
                'unique_together': {('team', 'gitlab_project_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('team', 'name')},
        ),
    ]
