# Generated by Django 4.1.5 on 2023-01-21 09:13

from django.db import migrations


def create_default_values(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    Column = apps.get_model('teams', 'Column')

    team = Team()
    team.name = 'Default'
    team.save()

    column_open = Column()
    column_open.name = 'Open'
    column_open.index = 1
    column_open.team = team
    column_open.save()

    column_closed = Column()
    column_closed.name = 'Closed'
    column_closed.index = 2
    column_closed.team = team
    column_closed.save()


def delete_default_values(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    Column = apps.get_model('teams', 'Column')

    Team.objects.filter(name='Default').delete()
    Column.objects.filter(name='Open').delete()
    Column.objects.filter(name='Closed').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_values, delete_default_values),
    ]
