# Generated by Django 4.1.7 on 2023-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_create_default_values'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='column',
            name='index',
            field=models.IntegerField(verbose_name='index'),
        )
    ]
