# Generated by Django 4.1.7 on 2023-04-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_column_unique_together_alter_column_index_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('team', 'name', 'index')},
        ),
    ]
