# Generated by Django 4.1.5 on 2023-01-21 09:13

from django.db import migrations


def create_default_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.create_superuser('admin', 'admin@gitlab.board', 'admin')


def delete_default_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_user, delete_default_user),
    ]
